### PR TITLE
Add tests to ensure that a date's millisecond part is persisted.

### PR DESCRIPTION
**Pull request by MrMage**
See https://github.com/vapor/postgresql/pull/29.

### CODE REVIEW

**Comment by MrMage** [comment]
Is there any CI set up for this, or is CI run only on the `fluent` repo?

**Comment by tanner0101** [comment]
@MrMage circle CI didn't have the option to build forked pull requests enabled. I've since enabled, but I think you must push another commit to trigger the tests.

**Comment by tanner0101** [comment]
Actually, was able to trigger it with the good ol' close and reopen. :)

**Comment by tanner0101** [comment]
Annoying branching stuff, ignore the failing test. Thanks!

**Pull request merged**
